### ISSUE TITLE
how do i suscribe to another peer?

### ISSUE THREAD

**Issue by el3ctron** [alifarazz/N2P#1]
hi! I'm trying your software, i read your documentation but i don't see how do i subscribe to another peer? Thanks for your answer.

**Comment by alifarazz** [comment]
Hi,
So assuming you have brought up 2 peers like this:
```bash
$ python peer/peer.py 127.0.0.1:8001 127.0.0.1:8002
```
and
```bash
$ python peer/peer.py 127.0.0.1:9001 127.0.0.1:9002
```
let's call the first one A and the second one B, and you want peer A to subscribe to peer B.
<hl>
So we need to issue a command to A so that it'll connect to B. Therefore, you'll have to connect to the control socket of A. You can do this using `netcat` program:
```bash
$ nc 127.0.0.1 8002
```
If the connection is successful, A will show a message about an "admin connection" being made (You may think that `nc` has hanged because it doesn't show much output, but actually it's waiting for input.). From there, you just have to issue an "ACTION" command to A using the admin connection you just made using `nc`: (Copy-paste this into `nc`)
```bash
$ nc 127.0.0.1 8002
{"ACTION": "CONNECT", "IP":"127.0.0.1", "PORT": "9001"}
```
Notice that you have to put the address to B's server socket which is, the first argument when calling `peer/peer.py`, `127.0.0.1:9001`. If A successfully connects to B, A will show a message about connecting to B's server and B will show a message about a client connecting to it.

**Comment by alifarazz** [comment]
Hey @el3ctron
Did I answer your question completely?
If not, please point out the ambiguities that may still remain.
